#!/bin/bash
# Night Shift - Autonomous Development While You Sleep

PROJECT_DIR="/home/shuakipie/Projects/koopprijs"
REPORT_FILE="$HOME/.clawdbot/memory/sessions/night-shift-$(date +%Y-%m-%d).md"
START_TIME=$(date +%s)

echo "🌙 Starting Night Shift - Autonomous Development"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Time: $(date)"
echo "Project: $PROJECT_DIR"
echo ""

# Initialize report
cat > "$REPORT_FILE" << EOF
# 🌙 Night Shift Report - $(date +%Y-%m-%d)

## Overview
Started: $(date +"%Y-%m-%d %H:%M:%S")
Project: koopprijs

---

## Actions Taken

EOF

cd "$PROJECT_DIR" || exit 1

# Safety: Create backup branch
BACKUP_BRANCH="backup/night-shift-$(date +%Y%m%d)"
git checkout -b "$BACKUP_BRANCH" 2>/dev/null || git checkout main

echo "✅ Safety backup created: $BACKUP_BRANCH"
echo ""

# 1. Analyze current state
echo "📊 Step 1: Analyzing current state..."
echo ""

# Check for obvious issues
echo "### 1. Initial Analysis" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Frontend analysis
if [ -d "realwork-frontend-master" ]; then
    cd realwork-frontend-master
    
    echo "Checking frontend..." >> "$REPORT_FILE"
    
    # Check for ESLint errors
    if command -v npm &> /dev/null && [ -f "package.json" ]; then
        echo "Running ESLint..." >> "$REPORT_FILE"
        npm run lint --silent 2>&1 | head -20 >> "$REPORT_FILE" || true
    fi
    
    cd ..
fi

# 2. Run AI-powered fixes with RovoDev and Claude Code
echo "🔧 Step 2: Running AI-powered fixes..."
echo ""

bash ~/.clawdbot/skills/autonomous-dev-1.0.0/scripts/ai_powered_fixes.sh >> "$REPORT_FILE" 2>&1

# 2b. Run additional automated fixes
echo "🔧 Step 2b: Running additional automated fixes..."
echo ""

bash ~/.clawdbot/skills/autonomous-dev-1.0.0/scripts/auto_fix.sh >> "$REPORT_FILE" 2>&1

# 3. Run tests
echo "🧪 Step 3: Running tests..."
echo ""

bash ~/.clawdbot/skills/autonomous-dev-1.0.0/scripts/test_runner.sh >> "$REPORT_FILE" 2>&1

# 4. Debug failures
echo "🐛 Step 4: Analyzing failures..."
echo ""

bash ~/.clawdbot/skills/autonomous-dev-1.0.0/scripts/debug_analyzer.sh >> "$REPORT_FILE" 2>&1

# 5. Commit changes if any
echo "💾 Step 5: Saving progress..."
echo ""

if [ -n "$(git status -s)" ]; then
    git add .
    git commit -m "🤖 Night Shift: Automated fixes and improvements

- Fixed linting errors
- Ran tests
- Improved code quality
- Analyzed and fixed bugs

Generated by autonomous night shift on $(date +%Y-%m-%d)" >> "$REPORT_FILE" 2>&1
    
    echo "✅ Changes committed" >> "$REPORT_FILE"
else
    echo "ℹ️  No changes to commit" >> "$REPORT_FILE"
fi

# 6. Generate summary
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))
MINUTES=$((DURATION / 60))

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "## Summary" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "Completed: $(date +"%Y-%m-%d %H:%M:%S")" >> "$REPORT_FILE"
echo "Duration: $MINUTES minutes" >> "$REPORT_FILE"
echo "Status: ✅ Night shift complete" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "Report saved to: $REPORT_FILE" >> "$REPORT_FILE"

# Generate morning report
bash ~/.clawdbot/skills/autonomous-dev-1.0.0/scripts/morning_report.sh

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Night shift complete!"
echo "📄 Report: $REPORT_FILE"
echo "⏰ Duration: $MINUTES minutes"
echo ""
